### ISSUE TITLE
Use better analysis_options

### ISSUE THREAD

**Issue by vanlooverenkoen** [icapps/combined_barcode_scanner#5]
```
include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    missing_required_param: error
    missing_return: error
    todo: ignore
    sdk_version_async_exported_from_core: ignore
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false
  exclude:
    - '**.mocks.dart'
    - 'lib/util/license.dart'
    - 'test/coverage_helper_test.dart'

linter:
  rules:
    - unawaited_futures
    - always_declare_return_types
    - unsafe_html
    - use_full_hex_values_for_flutter_colors
    - prefer_final_in_for_each
    - prefer_final_fields
    - prefer_final_locals
```
