### ISSUE TITLE
Not found FastBarcodeScanner()

### ISSUE THREAD

**Issue by manumathew17** [icapps/combined_barcode_scanner#8]
`     FastBarcodeScanner(),
          HoneywellBarcodeScanner(),
          UnitechBarcodeScanner(),
          BlueBirdBarcodeScanner(),
          ZebraBarcodeScanner('my_profile'),`

version combined_barcode_scanner: ^0.0.1-dev.1

**Comment by ikbendewilliam** [comment]
There is an issue downstream that blocks us from fully releasing this package. You can use it using git tags, for example:

```yaml
dependencies:
  combined_barcode_scanner: 0.0.1-dev.1
  combined_barcode_scanner_fast:
    git:
      url: git://github.com/icapps/combined_barcode_scanner.git
      path: pkgs/fast_barcode_scanner
  combined_barcode_scanner_unitech:
    git:
      url: git://github.com/icapps/combined_barcode_scanner.git
      path: pkgs/unitech
  combined_barcode_scanner_honeywell:
    git:
      url: git://github.com/icapps/combined_barcode_scanner.git
      path: pkgs/honeywell
  combined_barcode_scanner_zebra:
    git:
      url: git://github.com/icapps/combined_barcode_scanner.git
      path: pkgs/zebra_datawedge
  combined_barcode_scanner_blue_bird:
    git:
      url: git://github.com/icapps/combined_barcode_scanner.git
      path: pkgs/blue_bird_scanner
...

dependency_overrides:
  combined_barcode_scanner:
    git:
      url: git://github.com/icapps/combined_barcode_scanner.git
      ref: feature/6-extra-controller-methods
  fast_barcode_scanner:
    git:
      url: git://github.com/ikbendewilliam/fast_barcode_scanner.git
      path: fast_barcode_scanner
  fast_barcode_scanner_platform_interface:
    git:
      url: git://github.com/ikbendewilliam/fast_barcode_scanner.git
      path: fast_barcode_scanner_platform_interface
```
